DROP TRIGGER IF EXISTS trigger_set_due_date ON LENDING;
DROP TRIGGER IF EXISTS trigger_set_return_date ON LENDING;
DROP FUNCTION IF EXISTS set_due_date();
DROP FUNCTION IF EXISTS set_return_date();

DROP TABLE IF EXISTS ADDRESS CASCADE;
DROP TABLE IF EXISTS CONTACT CASCADE;
DROP TABLE IF EXISTS LENDING CASCADE;
DROP TABLE IF EXISTS REVIEW CASCADE;
DROP TABLE IF EXISTS WAITLIST CASCADE;
DROP TABLE IF EXISTS BOOK CASCADE;
DROP TABLE IF EXISTS KEYWORD CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;
