--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: set_due_date(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_due_date() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.DUE_DATE := NEW.CHECKOUT_DATE + INTERVAL '28 days';
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_due_date() OWNER TO postgres;

--
-- Name: set_return_date(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_return_date() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.STATUS = 'returned' AND OLD.STATUS = 'borrowed' THEN
        NEW.RETURN_DATE := CURRENT_DATE;
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_return_date() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    address_id integer NOT NULL,
    user_id integer,
    street character varying(200),
    housenumber character varying(50),
    city character varying(90),
    zip_code character varying(50)
);


ALTER TABLE public.address OWNER TO postgres;

--
-- Name: address_address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    book_id integer NOT NULL,
    isbn_long character varying(17) NOT NULL,
    isbn_short character varying(13),
    copies integer NOT NULL,
    booktitle character varying(500) NOT NULL,
    bookauthor character varying(200) NOT NULL,
    publisher character varying(400) NOT NULL,
    year_published integer,
    description character varying(10000),
    status character varying(100) DEFAULT 'available'::character varying,
    keyword_id integer,
    CONSTRAINT book_copies_check CHECK ((copies >= 0)),
    CONSTRAINT book_year_published_check CHECK (((year_published >= 1000) AND ((year_published)::numeric <= EXTRACT(year FROM CURRENT_DATE))))
);


ALTER TABLE public.book OWNER TO postgres;

--
-- Name: book_book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN book_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact (
    contact_id integer NOT NULL,
    user_id integer,
    email character varying(200) NOT NULL,
    phone character varying(50),
    mobile character varying(50)
);


ALTER TABLE public.contact OWNER TO postgres;

--
-- Name: contact_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact ALTER COLUMN contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keyword; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.keyword (
    keyword_id integer NOT NULL,
    keyword character varying(100) NOT NULL
);


ALTER TABLE public.keyword OWNER TO postgres;

--
-- Name: keyword_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.keyword ALTER COLUMN keyword_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keyword_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lending; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lending (
    lending_id integer NOT NULL,
    book_id integer,
    user_id_borrower integer,
    user_id_worker integer,
    status character varying(100) DEFAULT 'borrowed'::character varying,
    checkout_date date NOT NULL,
    return_date date,
    due_date date
);


ALTER TABLE public.lending OWNER TO postgres;

--
-- Name: lending_lending_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lending ALTER COLUMN lending_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lending_lending_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    user_id integer NOT NULL,
    firstname character varying(200) NOT NULL,
    lastname character varying(200) NOT NULL,
    birthdate date NOT NULL,
    gender character(1) NOT NULL,
    role character(50) NOT NULL,
    CONSTRAINT person_gender_check CHECK ((gender = ANY (ARRAY['M'::bpchar, 'F'::bpchar])))
);


ALTER TABLE public.person OWNER TO postgres;

--
-- Name: person_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
    review_id integer NOT NULL,
    book_id integer,
    user_id integer,
    review_text character varying(1000) NOT NULL,
    review_date date NOT NULL,
    review_rating character varying(10) NOT NULL
);


ALTER TABLE public.review OWNER TO postgres;

--
-- Name: review_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: waitlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.waitlist (
    waitlist_id integer NOT NULL,
    user_id integer,
    book_id integer,
    checkout_date date NOT NULL,
    return_date date,
    status character varying(100) DEFAULT 'waiting'::character varying
);


ALTER TABLE public.waitlist OWNER TO postgres;

--
-- Name: waitlist_waitlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.waitlist ALTER COLUMN waitlist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.waitlist_waitlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.address (address_id, user_id, street, housenumber, city, zip_code) FROM stdin;
1	1	Hauptstraße	1	Berlin	10115
2	2	Musterweg	42A	Hamburg	20095
3	3	Bahnhofstraße	99	München	80331
4	4	Friedrichstraße	15	Köln	50667
5	5	Berliner Platz	3B	Frankfurt	60311
6	6	Parkallee	27	Stuttgart	70173
7	7	Marktplatz	12	Düsseldorf	40213
8	8	Schulstraße	88	Dresden	01067
9	9	Bachstraße	9	Leipzig	04109
10	10	Kirchgasse	44	Bremen	28195
11	11	Lindenweg	56A	Hannover	30159
12	12	Seestraße	23	Nürnberg	90402
13	13	Am Rathaus	7	Essen	45127
14	14	Poststraße	66	Dortmund	44135
15	15	Flughafenstraße	18	Duisburg	47051
16	16	Schlossallee	5	Bochum	44787
17	17	Königsallee	88B	Wuppertal	42103
18	18	Steinstraße	31	Bielefeld	33602
19	19	Grüner Weg	21	Bonn	53111
20	20	Ringstraße	100	Münster	48143
21	21	Hafenstraße	15C	Karlsruhe	76133
22	22	Industriestraße	90	Mannheim	68159
23	23	Weinbergweg	3	Augsburg	86150
24	24	Am Zoo	77	Wiesbaden	65183
25	25	Goethestraße	4A	Gelsenkirchen	45879
26	26	Kulturstraße	12	Mönchengladbach	41061
27	27	Universitätsstraße	55	Braunschweig	38100
28	28	Sportplatzstraße	7	Chemnitz	09111
29	29	Albertstraße	92	Kiel	24103
30	30	Schlossstraße	6	Aachen	52062
31	31	Grabenstraße	19	Magdeburg	39104
32	32	Am Markt	45	Halle	06108
33	33	Theaterstraße	33	Freiburg	79098
34	34	Bahnhofplatz	2	Krefeld	47798
35	35	Schillerstraße	80	Lübeck	23552
36	36	Neuer Weg	14	Oberhausen	46045
37	37	Waldstraße	67	Erfurt	99084
38	38	Hofstraße	23	Rostock	18055
39	39	Brunnenstraße	8	Potsdam	14467
40	40	Hauptplatz	32	Saarbrücken	66111
41	41	Am Hang	99	Hamm	59065
42	42	Am Fluss	1B	Ludwigshafen	67059
43	43	Alte Gasse	57	Oldenburg	26122
44	44	Mittelstraße	3C	Leverkusen	51373
45	45	Sandweg	7	Osnabrück	49074
46	46	Buchenweg	42	Solingen	42651
47	47	Am See	21	Heidelberg	69115
48	48	Eichenstraße	9	Darmstadt	64283
49	49	Lärchenweg	77	Paderborn	33098
50	50	Heidestraße	11A	Regensburg	93047
51	51	Hauptstraße	1	Berlin	10115
52	52	Musterweg	42A	Hamburg	20095
53	53	Bahnhofstraße	99	München	80331
54	54	Friedrichstraße	15	Köln	50667
55	55	Berliner Platz	3B	Frankfurt	60311
56	56	Parkallee	27	Stuttgart	70173
57	57	Marktplatz	12	Düsseldorf	40213
58	58	Schulstraße	88	Dresden	01067
59	59	Bachstraße	9	Leipzig	04109
60	60	Kirchgasse	44	Bremen	28195
61	61	Lindenweg	56A	Hannover	30159
62	62	Seestraße	23	Nürnberg	90402
63	63	Am Rathaus	7	Essen	45127
64	64	Poststraße	66	Dortmund	44135
65	65	Flughafenstraße	18	Duisburg	47051
66	66	Schlossallee	5	Bochum	44787
67	67	Königsallee	88B	Wuppertal	42103
68	68	Steinstraße	31	Bielefeld	33602
69	69	Grüner Weg	21	Bonn	53111
70	70	Ringstraße	100	Münster	48143
71	71	Hafenstraße	15C	Karlsruhe	76133
72	72	Industriestraße	90	Mannheim	68159
73	73	Weinbergweg	3	Augsburg	86150
74	74	Am Zoo	77	Wiesbaden	65183
75	75	Goethestraße	4A	Gelsenkirchen	45879
76	76	Kulturstraße	12	Mönchengladbach	41061
77	77	Universitätsstraße	55	Braunschweig	38100
78	78	Sportplatzstraße	7	Chemnitz	09111
79	79	Albertstraße	92	Kiel	24103
80	80	Schlossstraße	6	Aachen	52062
81	81	Grabenstraße	19	Magdeburg	39104
82	82	Am Markt	45	Halle	06108
83	83	Theaterstraße	33	Freiburg	79098
84	84	Bahnhofplatz	2	Krefeld	47798
85	85	Schillerstraße	80	Lübeck	23552
86	86	Neuer Weg	14	Oberhausen	46045
87	87	Waldstraße	67	Erfurt	99084
88	88	Hofstraße	23	Rostock	18055
89	89	Brunnenstraße	8	Potsdam	14467
90	90	Hauptplatz	32	Saarbrücken	66111
91	91	Am Hang	99	Hamm	59065
92	92	Am Fluss	1B	Ludwigshafen	67059
93	93	Alte Gasse	57	Oldenburg	26122
94	94	Mittelstraße	3C	Leverkusen	51373
95	95	Sandweg	7	Osnabrück	49074
96	96	Buchenweg	42	Solingen	42651
97	97	Am See	21	Heidelberg	69115
98	98	Eichenstraße	9	Darmstadt	64283
99	99	Lärchenweg	77	Paderborn	33098
100	100	Heidestraße	11A	Regensburg	93047
\.


--
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book (book_id, isbn_long, isbn_short, copies, booktitle, bookauthor, publisher, year_published, description, status, keyword_id) FROM stdin;
1	978-3-16-148410-0	9517534862	2	Datenbanken Grundlagen	Max Mustermann	Fachverlag	2020	Einführung in Datenbanken	available	1
2	978-1-23-456789-7	7539514862	3	Programmieren für Einsteiger	Julia Muster	TechBooks	2019	Grundlagen der Programmierung	available	2
3	978-0-14-312547-1	5639464648	4	Big Data und NoSQL	Hannes Krieger	TechWorld	2021	Einführung in NoSQL und Big Data Technologien	available	3
4	978-0-16-148410-2	9513574862	5	Machine Learning Grundlagen	Maria Schmidt	AI Books	2020	Einführung in Machine Learning Konzepte	available	4
5	978-1-50-117321-8	2468135790	1	Algorithmen und Datenstrukturen	Thomas Lange	CompSci Verlag	2015	Grundlagen der Algorithmen und Datenstrukturen	borrowed	2
6	978-1-43-026778-0	1238765743	1	Datenbanken für Fortgeschrittene 2	Markus Müller	Informatik Verlag	2017	Erweiterte Datenbanktechniken	available	1
7	978-0-12-374979-9	1234567890	3	Python für Anfänger 1	Lena Braun	CodeBooks	2022	Python-Programmierung für Einsteiger	checked out	2
8	978-1-84-800003-6	4445554444	4	Java und OOP	Kurt Keller	DeveloperPress	2016	Objektorientierte Programmierung mit Java	available	3
9	978-3-16-148110-3	1065478974	3	Webentwicklung mit HTML und CSS	Nina Fischer	WebTech	2021	Grundlagen der Webentwicklung	available	4
10	978-0-13-708107-3	7899999999	1	JavaScript für Einsteiger	Lucas Herrmann	Frontend Verlag	2020	Einsteigerkurs in JavaScript	borrowed	4
11	978-0-13-708107-4	1593574862	1	Statistik für Data Science	Clara Berger	DataWorld	2021	Einführung in statistische Konzepte	available	3
12	978-3-16-248410-5	9981776522	2	Grundlagen der Netzwerksicherheit	Philipp Maier	Security Press	2019	Netzwerksicherheitskonzepte	borrowed	5
13	978-0-13-708107-6	9802345768	1	Künstliche Intelligenz	Daniel Kaiser	TechBooks	2018	Überblick über Künstliche Intelligenz	available	4
14	978-0-13-708107-7	2763837484	6	Systemarchitektur für IT	Sandra Frank	IT Pro	2020	Architekturen für moderne IT-Systeme	available	2
15	978-3-26-148410-6	6555554444	9	Objektorientierte Analyse und Design	Bernd Klein	OOAD Verlag	2015	Grundlagen der objektorientierten Analyse	borrowed	4
16	978-1-63-322710-1	1999999999	10	SQL für Einsteiger	Anna Lehmann	SQL Press	2017	Einsteigerkurs für SQL	available	1
17	978-1-16-148410-8	2999999999	3	Data Science Konzepte	Mara Hoffmann	DataBooks	2019	Wichtige Konzepte für Data Science	available	3
18	978-3-16-142410-9	4444445554	7	Visualisierung mit Tableau	Kevin Schmitt	Tableau Press	2021	Einführung in die Datenvisualisierung mit Tableau	borrowed	2
19	978-0-12-374968-3	6667776666	2	Einführung in Datenanalyse	Leon Schwarz	Analytics Verlag	2018	Grundlagen der Datenanalyse	available	1
20	978-0-16-148410-0	9333333337	10	Cloud Computing Grundlagen	Paul Steiner	CloudTech	2020	Konzepte des Cloud Computing	borrowed	5
21	978-1-23-456789-8	2333444278	5	Deep Learning Basics	Sabrina Weber	AI Books	2019	Grundlagen des Deep Learning	available	4
22	978-0-14-312547-2	1239800049	8	Cybersecurity Essentials	Johanna Kurz	Security Verlag	2021	Grundlagen der Cybersicherheit	available	2
23	978-1-47-321678-1	2122211121	9	Datenmanagement in der Praxis	Tobias Schmid	Data Verlag	2016	Praktische Datenmanagement-Konzepte	borrowed	1
24	978-1-23-456789-9	1000030001	14	Frontend-Entwicklung	Karl Zimmer	WebWorks	2020	Grundlagen für die Frontend-Entwicklung	available	3
25	978-0-13-708107-8	2111221111	3	Backend-Programmierung mit Node.js	Lisa Bauer	BackendBooks	2019	Node.js für Backend-Entwicklung	borrowed	4
26	978-1-16-148410-1	9111222834	9	DevOps für Einsteiger	Finn Seidel	TechFlow	2018	Grundlagen der DevOps-Praxis	available	5
27	978-3-16-148430-7	1209876543	9	Programmieren mit C++	Moritz Winter	TechPress	2022	C++ Programmierung für Einsteiger	borrowed	2
28	978-1-63-322710-2	9645364563	11	Einführung in R	Susanne Sommer	DataWorks	2017	R-Programmierung für Data Science	available	4
29	978-1-23-456789-0	7223889873	1	Konzepte der Datenbankoptimierung	Hanna Weigel	DB Verlag	2016	Optimierungstechniken für Datenbanken	borrowed	1
30	978-0-14-312547-3	1111131111	4	Software Engineering Basics	Marco Vogel	Software Verlag	2021	Grundlagen des Software Engineerings	available	3
31	978-1-47-321678-2	3333333323	5	Fortgeschrittene Web-Technologien	Claudia Lang	Web Innovators	2019	Fortgeschrittene Themen für die Webentwicklung	available	2
32	978-1-63-322710-3	7773337467	13	Blockchain und Kryptowährungen	Tom Kühn	CryptoPress	2018	Einführung in Blockchain-Technologie	borrowed	5
33	978-0-12-374968-4	3434343434	4	Agiles Projektmanagement	Rita Stark	PM Verlag	2020	Agile Methoden für Projektmanagement	available	3
34	978-0-16-148410-3	9173954735	9	Datenbanken für Fortgeschrittene 1	Uwe Schmidt	DB Verlag	2017	Fortgeschrittene Datenbankthemen	available	1
35	978-0-12-374968-5	7836666666	1	IT-Sicherheit Grundlagen	Norbert Weiß	SecurityPro	2021	Grundlagen der IT-Sicherheit	available	5
36	978-1-47-321678-3	2322200009	2	E-Commerce Technologien	Jan König	Commerce Verlag	2019	Technologien für E-Commerce Systeme	borrowed	3
37	978-0-13-708107-9	1110001110	1	Data Engineering Basics	Birgit Lutz	Data Verlag	2020	Grundlagen des Data Engineerings	available	2
38	978-1-23-456789-1	2122222222	3	Digitalisierung im Unternehmen	Otto Groß	Digital Press	2018	Digitalisierungskonzepte	borrowed	4
39	978-3-16-148410-1	9012229489	2	Data Science 101	Maria Weber	TechBooks	2015	An introduction to Data Science fundamentals.	available	1
40	978-3-16-148410-2	9988776522	1	Python für Anfänger 2	Thomas Müller	CodeMedia	2018	A comprehensive guide to Python programming for beginners.	borrowed	2
41	978-3-16-148410-3	2226356472	1	Java in Depth	Sandra Schmid	DevPress	2016	Advanced Java programming techniques and best practices.	available	3
42	978-3-16-148410-4	1000000001	1	Machine Learning Essentials	Laura Richter	AI Books	2019	A beginner-friendly guide to machine learning concepts.	reserved	4
43	978-3-16-148410-5	1000000002	2	C++ in der Praxis	Felix Lang	TechWorld	2017	Practical applications and examples in C++ programming.	borrowed	5
44	978-3-16-148410-6	1000000003	3	Die Welt der Algorithmen	Lisa Braun	InformatikVerlag	2020	A deep dive into algorithm design and analysis.	available	6
45	978-3-16-148410-7	1000000004	4	Datenstrukturen leicht gemacht	Martin Becker	ComputerBooks	2015	Fundamentals of data structures with practical examples.	borrowed	1
46	978-3-16-148410-8	1000000005	5	JavaScript Basics	Nina Fischer	WebDev Publishers	2019	An introduction to JavaScript for web development.	available	2
47	978-3-16-148410-9	1000000006	6	Projektmanagement in IT	Peter Hoffmann	BusinessBooks	2018	Managing projects in the tech industry effectively.	available	3
48	978-3-16-148411-0	1000000007	7	Künstliche Intelligenz für Anfänger	Alexandra Meyer	FutureTech	2020	An introduction to artificial intelligence concepts.	reserved	4
49	978-3-16-148411-1	1000000008	8	Big Data Grundlagen	Oliver Müller	DataPress	2017	Exploring the basics of Big Data technologies.	borrowed	5
50	978-3-16-148411-2	1000000009	9	SQL und Datenbanken	Emma Schmidt	CodeMedia	2016	A practical guide to SQL and relational databases.	available	6
51	978-3-16-148411-3	2000000001	1	Linux Administration	Tim Berger	SysAdmin Books	2015	Essential knowledge for Linux system administrators.	borrowed	1
52	978-3-16-148411-4	2000000002	2	Cloud Computing für Unternehmen	Sandra Keller	CloudPress	2019	Implementing cloud solutions for businesses.	available	2
53	978-3-16-148411-5	2000000003	4	Netzwerksicherheit	Sebastian Lorenz	CyberBooks	2018	Protecting networks from cyber threats.	reserved	3
54	978-3-16-148411-6	2000000004	4	Agile Entwicklungsmethoden	Tobias Schneider	IT Management	2016	Introduction to Agile and Scrum methodologies.	borrowed	4
55	978-3-16-148411-7	2000000005	4	Android Programmierung	Julia Fischer	MobileDev	2017	Developing applications for Android devices.	available	5
56	978-3-16-148411-8	2274350598	3	Software Testing	Fabian Weiß	TestWorld	2020	Best practices in software testing.	borrowed	6
57	978-3-16-148411-9	5779684565	1	Blockchain für Einsteiger	Melanie Klein	FutureTech	2019	A beginner’s guide to blockchain technology.	available	1
58	978-3-16-148412-0	9133487424	1	Cybersecurity Basics	Kevin Jung	SecBooks	2015	Understanding cybersecurity principles.	reserved	2
59	978-3-16-148412-1	2233086136	3	R für Datenanalyse	Thomas Keller	DataPress	2018	Data analysis with the R programming language.	borrowed	3
60	978-3-16-148412-2	3448828072	4	Digitales Marketing	Sarah Wagner	MarketingPro	2017	An overview of digital marketing strategies.	available	4
61	978-3-16-148412-3	4951489342	3	Fortgeschrittene Python-Programmierung	Lars Wolf	TechBooks	2020	Advanced techniques in Python programming.	borrowed	5
62	978-3-16-148412-4	7504242343	1	IT-Sicherheit	Max Weber	CyberPress	2019	Best practices for IT security management.	available	6
63	978-3-16-148412-5	5119785119	3	Datenvisualisierung	Anna Kaiser	VizBooks	2016	Data visualization techniques and tools.	borrowed	1
64	978-3-16-148412-6	2679082805	6	Scrum und Agile Methoden	Michael Franz	Agile Books	2018	Applying Scrum and Agile methodologies in projects.	available	2
65	978-3-16-148412-7	1059564553	3	Digitale Transformation	Clara Winkler	FutureTech	2019	Navigating digital transformation in organizations.	reserved	3
66	978-3-16-148412-8	0217346134	2	Webentwicklung mit HTML5 und CSS3	Frank Müller	WebDev Press	2017	Creating modern websites with HTML5 and CSS3.	borrowed	4
67	978-3-16-148412-9	3331583882	8	React für Einsteiger	Nina Ludwig	CodeMedia	2020	Introduction to React for front-end development.	available	5
68	978-3-16-148413-0	6582062333	5	Datenanalyse mit SQL	Simon Köhler	DataPress	2015	Analyzing data with SQL queries.	borrowed	6
69	978-3-16-148413-1	4216243299	3	Systemarchitektur	Uwe Becker	InformatikVerlag	2016	Designing scalable system architectures.	available	1
70	978-3-16-148413-2	0145629201	5	Einführung in Ruby	Leonie Fischer	RubyBooks	2018	Learning the Ruby programming language.	borrowed	2
71	978-3-16-148413-3	0543642213	3	Design Thinking	Tom Schuster	Creative Books	2017	Applying design thinking to innovation.	reserved	3
72	978-3-16-148413-4	8500725528	5	Kubernetes für Entwickler	Patrick Brandt	CloudPress	2019	Using Kubernetes for container management.	available	4
73	978-3-16-148413-5	8123300367	2	Künstliche neuronale Netze	Nina Schwarz	AI Books	2020	An introduction to neural networks.	borrowed	5
74	978-3-16-148413-6	4195205270	2	Cyber-Risiken in Unternehmen	Max Bauer	SecBooks	2018	Understanding and mitigating cyber risks.	available	6
75	978-3-16-148413-7	8261651843	4	Die Programmiersprache Go	Oliver König	DevPress	2017	An introduction to the Go programming language.	borrowed	1
76	978-3-16-148413-8	6414613095	2	Software-Engineering	Miriam Schmid	TechBooks	2015	Software development processes and methodologies.	available	2
77	978-3-16-148413-9	1196250167	1	JavaScript Frameworks	Lars Walter	WebDev Publishers	2019	A guide to popular JavaScript frameworks.	reserved	3
78	978-3-16-148414-0	5468309882	2	SQL für Fortgeschrittene	Klaus Weber	DataPress	2016	Advanced SQL techniques and practices.	borrowed	4
79	978-3-16-148414-1	1774371415	2	3D-Animation und Modellierung	Stefan Braun	GraphicsPro	2018	Creating 3D animations and models.	available	5
80	978-3-16-148414-2	900000384	1	Microservices Architektur	Petra Wolf	CloudPress	2020	Developing applications with microservices.	borrowed	6
81	978-3-16-148414-3	4622760045	5	IT-Projektmanagement	Birgit Lang	BusinessBooks	2017	Managing IT projects effectively.	available	1
82	978-3-16-148414-4	0799165772	4	Digitalisierung in der Industrie	Helmut Richter	IndustrialBooks	2019	Digital transformation in the industrial sector.	borrowed	2
83	978-3-16-148414-5	1907977995	2	Einführung in NoSQL	Carina Ludwig	DataPress	2015	Exploring NoSQL databases and their applications.	available	3
84	978-3-16-148414-6	7772692814	2	Kreatives Programmieren	Tobias Busch	Creative Books	2016	Coding creatively with Processing and p5.js.	borrowed	4
85	978-3-16-148414-7	1193926872	2	Risikomanagement in der IT	Fabian Neumann	RiskBooks	2018	Managing risk in IT projects.	available	5
86	978-3-16-148414-8	8023939891	8	Web Design Trends	Vanessa Kurz	WebDev Publishers	2020	Latest trends in web design and UX.	reserved	6
87	978-3-16-148414-9	0081926301	2	Agile Transformation	Johannes Maier	Agile Books	2019	Implementing agile processes in organizations.	borrowed	1
88	978-1-61-729256-5	0557440352	4	Die letzten Sterne	Mia Schulze	SciFi Verlag	2023	Ein Weltraumabenteuer in einer fernen Zukunft	available	1
89	978-0-14-132323-3	6814524807	2	Magie der Drachen	Elena Wolf	Fantasy World	2022	Ein episches Abenteuer im Land der Drachen	borrowed	2
90	978-0-54-537718-7	8349589906	5	Der Fluch der Rosen	Jessica Meyer	Romance Verlag	2021	Eine verbotene Liebe zwischen zwei Welten	available	3
91	978-0-15-104549-5	0441299518	5	Der mysteriöse Fall	Oliver Schwarz	MysteryPress	2022	Ein unlösbarer Mordfall in einer kleinen Stadt	borrowed	4
92	978-1-23-456847-9	3168060260	3	Die Jagd	Sarah Becker	Thriller Verlag	2023	Ein Thriller über einen unerbittlichen Jäger	available	5
93	978-1-25-346938-3	2463665267	3	Blutmond	Lukas Jäger	Horror Verlag	2020	Dunkle Mächte und ein schreckliches Geheimnis	borrowed	6
94	978-3-16-415271-4	7227673315	2	Der Krieg der Könige	Katharina Stein	Historical Fiction Books	2021	Ein historischer Roman über Macht und Verrat	available	7
95	978-1-84-784206-7	2400641219	1	Die Insel der verlorenen Schätze	Thomas Schuster	Adventure Press	2022	Ein Abenteuer voller Geheimnisse und Schätze	borrowed	8
96	978-0-32-918435-5	2634530061	3	Der geheime Club	Anna Fischer	Young Adult Verlag	2021	Freundschaft und Geheimnisse in der Jugendzeit	available	9
97	978-1-41-657345-9	5023597566	2	Welt aus Asche	Felix Braun	Dystopian Books	2020	Eine Zukunft zerstört von Naturkatastrophen	borrowed	10
98	978-0-15-846236-9	4761007598	3	Die verborgene Welt	Monika Kraus	Paranormal Verlag	2022	Geheimnisse und übernatürliche Kräfte	available	11
99	978-1-58-832046-9	6848065000	1	Im Schatten des Zweifels	Robert Peters	Contemporary Verlag	2021	Ein Roman über Liebe, Verlust und Vertrauen	borrowed	12
100	978-1-45-237741-8	4621262920	1	Ein Leben in Worten	Jessica Fischer	Biography Press	2023	Die Geschichte eines außergewöhnlichen Lebens	available	13
101	978-1-56-672934-6	9111134213	2	In Erinnerung an den Krieg	Markus Braun	Memoir Verlag	2022	Ein persönliches Memoir über das Leben nach dem Krieg	borrowed	14
102	978-1-68-722409-5	9698231068	9	Der Weg der Veränderung	Simon Müller	Non-fiction Books	2021	Ein Buch über persönliche Entwicklung und Veränderung	available	15
103	978-0-14-127844-4	4621760045	1	Kraft der Gedanken	Eva Schulz	Self-help Verlag	2020	Hilfreiche Tipps zur Steigerung des persönlichen Wohlbefindens	borrowed	16
104	978-0-98-765453-4	6036388423	1	Der Erfolgscode	Julian Weber	Business Verlag	2022	Erfolgsstrategien für Unternehmer und Selbstständige	available	17
105	978-1-73-254892-6	3270370227	1	Die Kunst der Selbstfürsorge	Lena Becker	Health & Wellness Verlag	2021	Ein Leitfaden für ein gesundes und glückliches Leben	borrowed	18
106	978-1-45-675763-2	7008614729	1	Gesunde Küche	Miriam Klein	Cookbook Press	2020	Leckere Rezepte für eine ausgewogene Ernährung	available	19
107	978-0-98-734208-3	5500150166	8	Die Farben der Welt	Paul Richter	ArtBooks	2021	Ein Kunstbuch über die Bedeutung von Farben in der Kunst	borrowed	20
108	978-1-84-323073-7	5010714745	2	Gedichte der Nacht	Clara Vogel	Poetry Press	2022	Eine Sammlung von düsteren und nachdenklichen Gedichten	available	21
109	978-1-62-118430-0	7508317679	3	Die Unendlichkeit des Augenblicks	Jana Weber	ClassicBooks	2021	Ein klassischer Roman über die Unvermeidlichkeit des Schicksals	borrowed	22
110	978-0-12-349672-3	9308618245	4	Der Lächelnsplan	Eva Heidrich	Humor Press	2022	Lachen als Lebensstrategie – ein humorvolles Sachbuch	available	23
111	978-1-56-738129-4	0818830141	4	Die verlorenen Tage	Ursula Hoffmann	Children's Fiction Verlag	2020	Ein Kinderbuch über Freundschaft und Abenteuer	borrowed	24
112	978-3-15-948632-7	2403818633	1	Der große Traum	Felix Sturm	Literary Fiction Books	2022	Ein literarisches Meisterwerk über das Leben und seine Tragödien	available	25
113	978-1-13-489567-7	6036820037	1	Das düstere Geheimnis	Isabelle Reuter	CrimeBooks	2021	Ein Kriminalfall, der das Leben aller Beteiligten verändert	borrowed	26
114	978-1-43-248753-0	2413818633	1	Das düstere Netz	Markus Stein	True Crime Verlag	2022	Echte Kriminalfälle, die die Welt erschütterten	available	27
115	978-1-50-151848-2	3420751627	1	Das Geheimnis der Sterne	Andrea Weber	Science Verlag	2020	Wissenschaftliche Entdeckungen und ihre Bedeutung für die Zukunft	borrowed	28
116	978-1-54-654937-5	2476498345	3	Die geheime Natur	Johanna Fischer	NatureBooks	2021	Eine Reise in die Geheimnisse der Natur	available	29
117	978-3-16-715899-2	7735760294	1	Die Maschinen	Erik Müller	Technology Books	2022	Wie Maschinen die Zukunft verändern	borrowed	30
118	978-1-24-798596-4	5726252668	3	Die Philosophie des Lebens	Marcel Fischer	Philosophy Books	2021	Ein philosophischer Blick auf das Leben und seine Bedeutung	available	31
119	978-0-19-482982-1	2224490317	3	Psychologie des Glücks	Elena Hahn	Psychology Press	2020	Wie du dein Leben mit positiven Gedanken verändern kannst	borrowed	32
120	978-1-56-072804-7	3353574855	1	Das Geheimnis des Glaubens	Oliver Becker	Religion Verlag	2021	Ein philosophischer Blick auf Religion und Spiritualität	available	33
121	978-0-92-184396-4	8618399525	1	Der Weg zum inneren Frieden	Jana Huber	Spirituality Press	2022	Wie du deine innere Ruhe findest	borrowed	34
122	978-1-13-348172-6	2111989373	1	Die Welt bereisen	Max Schuster	TravelBooks	2021	Reiseberichte aus den entlegensten Teilen der Erde	available	35
123	978-1-25-374901-8	7111111112	3	Der Klang der Musik	Eva Krüger	Music Press	2020	Eine Reise durch die Welt der Musik und ihrer Geschichte	borrowed	36
\.


--
-- Data for Name: contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contact (contact_id, user_id, email, phone, mobile) FROM stdin;
1	1	shawkin0@artisteer.com	3927021722	2553336456
2	2	gcastletine1@yellowpages.com	1146846492	5003019881
3	3	pbatiste2@cyberchimps.com	9575050182	3268089625
4	4	fsimeoli3@skyrock.com	9259507781	1229822294
5	5	ostockau4@bandcamp.com	3679857054	5599598991
7	7	awhistan6@apple.com	4413299042	6316999600
8	8	bgounard7@simplemachines.org	3462200368	2166601037
9	9	aarunowicz8@over-blog.com	3862132226	1266794118
10	10	bbedson9@smh.com.au	6647529207	8544156134
12	12	kgilstinb@desdev.cn	8934407616	4722047386
13	13	ostationc@hao123.com	7667658634	5664320948
14	14	lrappd@guardian.co.uk	4233397190	8718556873
15	15	pshoreye@fda.gov	1001481543	5788478696
16	16	npetof@jalbum.net	6608391891	6039074793
17	17	mellcomeg@elegantthemes.com	3365771482	1347270406
18	18	dstaigh@intel.com	3465028575	7205932222
19	19	aworlidgei@taobao.com	5847273817	3092798419
20	20	aricketj@hugedomains.com	6136707525	2402941329
21	21	pkatzk@webs.com	8259477463	7267626079
22	22	rkmiecl@vkontakte.ru	1188688974	6127702573
23	23	aszachniewiczm@google.fr	7104739750	4642976010
24	24	atulkn@github.io	8141126808	7281957702
25	25	ggaffono@hugedomains.com	8546824198	3597723083
26	26	kdanap@qq.com	5341074751	8128519965
27	27	ahassettq@rakuten.co.jp	2054819364	8007221893
28	28	ppoytresr@yellowbook.com	6289132789	8993114545
29	29	amccathies@statcounter.com	3026786391	5212564564
30	30	ccortert@nydailynews.com	7541983370	8373909777
31	31	ahymanu@nyu.edu	8959980880	9253589975
32	32	tcrosscombev@cpanel.net	8527182233	4477992412
33	33	ybellowsw@yandex.ru	9505280825	5451445221
34	34	greidex@mediafire.com	7532734897	4019910585
35	35	mizakovitzy@godaddy.com	4255156574	3914296013
36	36	tpiattoz@cloudflare.com	3099228754	4604362372
37	37	gmitskevich10@go.com	6073008672	4452977311
38	38	amccrostie11@mac.com	1824879567	3705596738
39	39	gyurocjhin12@accuweather.com	7029727913	1864824513
40	40	nbinch13@ibm.com	1332943715	6927809461
41	41	bcoltherd14@businesswire.com	6157830313	3045657941
42	42	dmourton15@typepad.com	6056983153	7928531010
43	43	jibbett16@state.tx.us	5909144448	3866021761
44	44	mmendez17@bravesites.com	4987109355	3583750022
45	45	rboddington18@youtu.be	8355623646	2633693489
46	46	lghion19@photobucket.com	9095581476	9237829322
47	47	sgaveltone1a@zdnet.com	2746967107	4309653306
48	48	clangrish1b@imgur.com	6992451308	9259717410
49	49	msapp1c@princeton.edu	9109364124	6509584590
50	50	mlascelles1d@goo.gl	4547166967	5123742023
51	51	sstorah1e@netscape.com	4661359602	6076180106
52	52	asive1f@army.mil	7625824030	8679355526
53	53	sdaltrey1g@privacy.gov.au	8433376890	2839217221
54	54	mpanchen1h@feedburner.com	3616863812	7415151264
55	55	nmuris1i@google.cn	2023998828	6547752023
56	56	vdunston1j@usa.gov	4896871610	1478065003
57	57	fgregs1k@jugem.jp	9487526634	8364948552
58	58	aperks1l@icq.com	2329850691	4069647318
59	59	cboate1m@g.co	6657354332	4333727986
60	60	ggarstang1n@weibo.com	7439683249	9956888813
61	61	lslyman1o@istockphoto.com	8395718315	3695309257
62	62	tbrasher1p@linkedin.com	5017072242	5652053913
63	63	aodyvoie1q@infoseek.co.jp	7877884920	4297606779
64	64	rdenajera1r@tamu.edu	5017043437	8028119786
65	65	adosdill1s@i2i.jp	6296702160	6848694790
66	66	cbrain1t@ovh.net	8435196483	9056379247
67	67	fcasterot1u@wikimedia.org	5195578574	4305785970
68	68	dbeardall1v@mashable.com	8534091610	2094376931
69	69	dtabord1w@over-blog.com	4825150911	9425092649
70	70	dperone1x@harvard.edu	5532490533	8888508022
71	71	wmancktelow1y@yelp.com	1545127717	5506034982
72	72	ccornick1z@noaa.gov	4361533853	5628952090
73	73	dscimone20@reuters.com	1502346188	7255043777
74	74	hguiducci21@pinterest.com	9319524623	5865130067
75	75	lbarbie22@cdbaby.com	3921267431	3194927665
76	76	kblaisdell23@bluehost.com	8762023140	1822426215
77	77	parnold24@unc.edu	6604473075	8258321204
78	78	thurburt25@tamu.edu	2803495849	8217613713
79	79	sshowering26@acquirethisname.com	1616054240	3075568177
80	80	rhornig27@vimeo.com	3095924161	4906634346
81	81	ipiggin28@cafepress.com	2849215963	3968951269
82	82	nmccarrison29@t.co	2873798925	8098635240
83	83	rchattoe2a@cdc.gov	5765871236	8123615510
84	84	mbrightey2b@mysql.com	6127671534	6145390947
85	85	ccapin2c@webs.com	1557962402	5939510327
86	86	codrought2d@google.com.br	5757414872	9142247978
87	87	aloweth2e@mapy.cz	1959867278	9623481150
88	88	dsutworth2f@hibu.com	8025491491	5794701802
89	89	rianelli2g@sakura.ne.jp	8383371876	7009092769
90	90	cenoch2h@patch.com	7086733831	6579031951
91	91	abothie2i@nasa.gov	7967747122	1854093327
92	92	kblaxall2j@phoca.cz	1461972833	6339281121
93	93	lrichly2k@rakuten.co.jp	5449505575	2662009019
94	94	lcharkham2l@blog.com	6395445576	8798855709
95	95	pnorton2m@ftc.gov	2806523325	9277528706
96	96	dcollen2n@cafepress.com	1917697192	1411055600
97	97	syorath2o@deviantart.com	9163903107	4624386409
98	98	gplet2p@technorati.com	2179807914	6545612316
99	99	eleslie2q@umich.edu	4735847369	4781409373
100	100	jkinneir2r@google.co.uk	1893673056	5457356617
\.


--
-- Data for Name: keyword; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.keyword (keyword_id, keyword) FROM stdin;
1	Science Fiction
2	Fantasy
3	Romance
4	Mystery
5	Thriller
6	Horror
7	Historical Fiction
8	Adventure
9	Young Adult
10	Dystopian
11	Paranormal
12	Contemporary Fiction
13	Biography
14	Memoir
15	Non-fiction
16	Self-help
17	Business
18	Health & Wellness
19	Cookbook
20	Art
21	Poetry
22	Classic
23	Humor
24	Children's Fiction
25	Literary Fiction
26	Crime
27	True Crime
28	Science
29	Nature
30	Technology
31	Philosophy
32	Psychology
33	Religion
34	Spirituality
35	Travel
36	Music
37	Sports
38	Graphic Novel
39	Manga
40	Urban Fantasy
41	Steampunk
42	Cyberpunk
43	Fairy Tale
44	Western
45	Military Fiction
46	Historical Romance
47	Erotica
48	Short Stories
49	Anthology
50	New Adult
51	Dark Fantasy
52	Apocalyptic
53	Post-apocalyptic
54	Magical Realism
55	Psychological Thriller
56	Romantic Comedy
57	Action
58	Spy Fiction
59	Legal Thriller
60	Medical Fiction
61	Eco-fiction
62	Mythology
63	Family Drama
64	Satire
65	Coming-of-age
66	LGBTQ+ Fiction
67	Regency Romance
68	Courtroom Drama
69	Space Opera
70	Time Travel
71	Superhero Fiction
72	Alien Fiction
73	Vampire Fiction
74	Werewolf Fiction
75	Zombie Fiction
76	Witch Fiction
77	Shapeshifter Fiction
78	Detective Fiction
79	Espionage
80	Sea Adventure
81	Cooking Fiction
82	Language Learning
\.


--
-- Data for Name: lending; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lending (lending_id, book_id, user_id_borrower, user_id_worker, status, checkout_date, return_date, due_date) FROM stdin;
1	1	1	2	borrowed	2023-03-01	\N	2023-03-29
2	2	3	2	returned	2023-04-01	2023-04-10	2023-04-29
3	3	7	2	borrowed	2023-05-10	\N	2023-06-07
4	4	10	2	returned	2023-02-15	2023-02-28	2023-03-15
5	5	12	2	borrowed	2023-06-05	\N	2023-07-03
6	6	15	2	returned	2023-01-20	2023-01-30	2023-02-17
7	7	18	2	borrowed	2023-07-01	\N	2023-07-29
8	8	21	2	returned	2023-04-15	2023-04-22	2023-05-13
9	9	25	2	borrowed	2023-05-15	\N	2023-06-12
10	10	30	2	returned	2023-03-01	2023-03-10	2023-03-29
11	11	35	2	borrowed	2023-02-20	\N	2023-03-20
12	12	40	2	returned	2023-05-25	2023-06-01	2023-06-22
13	13	45	2	borrowed	2023-06-05	\N	2023-07-03
14	14	50	2	returned	2023-03-15	2023-03-25	2023-04-12
15	15	55	2	borrowed	2023-07-10	\N	2023-08-07
16	16	60	2	returned	2023-02-10	2023-02-20	2023-03-10
17	17	63	2	borrowed	2023-06-15	\N	2023-07-13
18	18	68	2	returned	2023-01-05	2023-01-15	2023-02-02
19	19	71	2	borrowed	2023-07-15	\N	2023-08-12
20	20	75	2	returned	2023-03-20	2023-03-25	2023-04-17
21	21	78	2	borrowed	2023-04-05	\N	2023-05-03
22	22	82	2	returned	2023-01-10	2023-01-15	2023-02-07
23	23	88	2	borrowed	2023-06-25	\N	2023-07-23
24	24	91	2	returned	2023-02-01	2023-02-10	2023-03-01
25	25	95	2	borrowed	2023-05-30	\N	2023-06-27
26	26	99	2	returned	2023-04-20	2023-04-28	2023-05-18
27	27	2	2	borrowed	2023-07-05	\N	2023-08-02
28	28	6	2	returned	2023-02-25	2023-03-03	2023-03-25
29	29	11	2	borrowed	2023-06-10	\N	2023-07-08
30	30	14	2	returned	2023-03-01	2023-03-12	2023-03-29
31	31	19	2	borrowed	2023-05-01	\N	2023-05-29
32	32	23	2	returned	2023-04-01	2023-04-08	2023-04-29
33	33	27	2	borrowed	2023-07-10	\N	2023-08-07
34	34	31	2	returned	2023-03-15	2023-03-25	2023-04-12
35	35	34	2	borrowed	2023-06-20	\N	2023-07-18
36	36	38	2	returned	2023-02-05	2023-02-15	2023-03-05
37	37	41	2	borrowed	2023-07-12	\N	2023-08-09
38	38	45	2	returned	2023-01-15	2023-01-22	2023-02-12
39	39	49	2	borrowed	2023-06-30	\N	2023-07-28
40	40	52	2	returned	2023-04-15	2023-04-22	2023-05-13
\.


--
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person (user_id, firstname, lastname, birthdate, gender, role) FROM stdin;
1	Anna	Müller	1990-04-15	F	borrower                                          
2	Max	Schneider	1985-06-22	M	worker                                            
3	Julia	Fischer	1978-11-10	F	borrower                                          
4	Leon	Weber	1992-03-05	M	borrower                                          
5	Sophia	Schmidt	1989-07-18	F	worker                                            
6	Paul	Meyer	1983-12-25	M	borrower                                          
7	Lena	Schulz	1995-09-12	F	borrower                                          
8	Felix	Becker	1988-01-30	M	worker                                            
9	Lisa	Hofmann	1991-05-20	F	borrower                                          
10	Tim	Koch	1986-08-08	M	borrower                                          
11	Emma	Bauer	1994-03-22	F	worker                                            
12	Jonas	Richter	1987-07-17	M	borrower                                          
13	Marie	Wagner	1990-11-14	F	borrower                                          
14	Ben	Neumann	1984-02-09	M	worker                                            
15	Lara	Schwarz	1993-06-25	F	borrower                                          
16	Noah	Zimmermann	1979-10-05	M	borrower                                          
17	Sarah	Schmitt	1982-04-02	F	worker                                            
18	David	Hartmann	1986-12-18	M	borrower                                          
19	Mia	Krüger	1996-08-29	F	borrower                                          
20	Tom	Schmid	1991-01-11	M	worker                                            
21	Lea	Pohl	1990-09-16	F	borrower                                          
22	Finn	Lange	1985-06-30	M	borrower                                          
23	Hannah	Simon	1988-02-13	F	worker                                            
24	Jan	Maier	1983-05-23	M	borrower                                          
25	Amelie	Walter	1994-11-08	F	borrower                                          
26	Niklas	König	1977-12-02	M	worker                                            
27	Sophie	Keller	1993-04-20	F	borrower                                          
28	Lucas	Fuchs	1987-07-14	M	borrower                                          
29	Nina	Schuster	1990-10-18	F	worker                                            
30	Elias	Brandt	1985-01-25	M	borrower                                          
31	Elena	Haas	1992-03-30	F	borrower                                          
32	Moritz	Hahn	1984-08-03	M	worker                                            
33	Clara	Scholz	1991-06-12	F	borrower                                          
34	Matthias	Ulrich	1979-02-22	M	borrower                                          
35	Isabel	Schubert	1993-11-05	F	worker                                            
36	Tobias	Horn	1982-12-17	M	borrower                                          
37	Eva	Werner	1987-09-27	F	borrower                                          
38	Fabian	Winkler	1986-07-10	M	worker                                            
39	Nele	Berg	1995-04-07	F	borrower                                          
40	Jannik	Möller	1990-05-15	M	borrower                                          
41	Katharina	Pfeiffer	1989-11-19	F	worker                                            
42	Sebastian	Ludwig	1984-03-13	M	borrower                                          
43	Antonia	Böhm	1996-02-28	F	borrower                                          
44	Alexander	Schröder	1985-12-21	M	worker                                            
45	Paula	Franke	1991-08-26	F	borrower                                          
46	Christian	Krause	1983-09-11	M	borrower                                          
47	Marlene	Voigt	1988-06-18	F	worker                                            
48	Simon	Heinrich	1994-10-22	M	borrower                                          
49	Franziska	Engel	1990-07-09	F	borrower                                          
50	Erik	Schneider	1982-05-01	M	worker                                            
51	Laura	Klein	1989-04-11	F	borrower                                          
52	Martin	Wolf	1991-10-14	M	worker                                            
53	Claudia	Kühn	1986-12-19	F	borrower                                          
54	Lukas	Schlegel	1987-08-22	M	borrower                                          
55	Helena	Busch	1980-03-15	F	worker                                            
56	Oliver	Franz	1978-09-20	M	borrower                                          
57	Theresa	Bergmann	1995-11-30	F	borrower                                          
58	Patrick	Otto	1990-06-07	M	worker                                            
59	Melanie	Koch	1985-02-18	F	borrower                                          
60	Bastian	Heller	1983-05-19	M	borrower                                          
61	Nadine	Frey	1994-09-26	F	worker                                            
62	Daniel	Jakob	1988-11-10	M	borrower                                          
63	Karina	Kaiser	1993-12-25	F	borrower                                          
64	Florian	Peters	1982-08-02	M	worker                                            
65	Johanna	Böttcher	1996-03-29	F	borrower                                          
66	Kilian	Lorenz	1991-01-18	M	borrower                                          
67	Miriam	Hauser	1984-07-04	F	worker                                            
68	Konstantin	Hennig	1979-10-09	M	borrower                                          
69	Veronika	Wendt	1986-06-15	F	borrower                                          
70	Sascha	Ebert	1990-09-22	M	worker                                            
71	Silvia	Bayer	1987-01-05	F	borrower                                          
72	Leonhard	Heinze	1985-04-11	M	borrower                                          
73	Jasmin	Brock	1992-07-23	F	worker                                            
74	Armin	Schuhmann	1977-12-08	M	borrower                                          
75	Carina	Voss	1995-02-26	F	borrower                                          
76	Marcel	Lang	1983-10-30	M	worker                                            
77	Denise	Brand	1994-05-27	F	borrower                                          
78	Michael	Wirth	1989-11-02	M	borrower                                          
79	Susanne	Geiger	1991-08-10	F	worker                                            
80	Ralf	Kraft	1984-03-12	M	borrower                                          
81	Jana	Schäfer	1988-01-17	F	borrower                                          
82	Thorsten	Schick	1992-04-20	M	worker                                            
83	Ulrike	Lindner	1985-06-09	F	borrower                                          
84	Tim	Braun	1987-08-14	M	borrower                                          
85	Alexandra	Roth	1990-10-18	F	worker                                            
86	Philipp	Korn	1978-09-27	M	borrower                                          
87	Angelika	Schuster	1981-05-06	F	borrower                                          
88	Robert	Haag	1993-12-15	M	worker                                            
89	Diana	Riedel	1984-02-11	F	borrower                                          
90	Holger	Nowak	1989-07-21	M	borrower                                          
91	Simone	Kraft	1986-10-30	F	worker                                            
92	Christian	Dorn	1991-01-23	M	borrower                                          
93	Sandra	Krebs	1995-03-09	F	borrower                                          
94	Sebastian	Götz	1987-11-05	M	worker                                            
95	Nora	Bühler	1982-04-26	F	borrower                                          
96	Dirk	Klünder	1988-12-30	M	borrower                                          
97	Manuela	Beck	1985-09-12	F	worker                                            
98	Jürgen	Schön	1994-06-28	M	borrower                                          
99	Petra	Mann	1980-07-18	F	borrower                                          
100	Gerhard	Seidel	1979-03-31	M	worker                                            
\.


--
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.review (review_id, book_id, user_id, review_text, review_date, review_rating) FROM stdin;
1	1	1	Sehr informatives Buch!	2023-03-01	5
2	2	2	Gut für Einsteiger.	2023-03-02	4
3	3	5	Interessante Perspektiven, aber zu langatmig.	2023-03-03	3
4	4	3	Faszinierende Charaktere und Plot!	2023-03-04	5
5	5	10	Kann ich nicht empfehlen, zu langweilig.	2023-03-05	2
6	6	7	Tolles Buch, aber das Ende war enttäuschend.	2023-03-06	4
7	7	1	Habe viel Neues gelernt, sehr aufschlussreich.	2023-03-07	5
8	8	15	Gut geschrieben, aber stellenweise zu kompliziert.	2023-03-08	3
9	9	2	Eine wahre Leseempfehlung!	2023-03-09	5
10	10	9	Gutes Buch, aber zu lang.	2023-03-10	4
11	11	8	Nicht mein Fall, zu viele Längen.	2023-03-11	2
12	12	6	Sehr gut recherchiert und spannend.	2023-03-12	5
13	13	11	Schwache Charakterentwicklung, aber gute Handlung.	2023-03-13	3
14	14	14	Ein Klassiker, der nie alt wird.	2023-03-14	5
15	15	12	Zu viele unaufgelöste Fragen.	2023-03-15	3
16	16	3	Würdig für die Sammlung, fesselnd und tiefgründig.	2023-03-16	5
17	17	20	Sehr schwache Story, nicht überzeugend.	2023-03-17	1
18	18	4	Ein wenig zu vorhersehbar.	2023-03-18	4
19	19	6	Ein Meisterwerk, muss man gelesen haben!	2023-03-19	5
20	20	10	Gut geschrieben, aber die Geschichte konnte mich nicht packen.	2023-03-20	3
21	21	17	Erfrischend anders und innovativ!	2023-03-21	5
22	22	1	Nicht so gut wie erwartet, aber immer noch lesenswert.	2023-03-22	4
23	23	16	Spannend bis zur letzten Seite.	2023-03-23	5
24	24	5	Habe den Hype nicht verstanden, war ganz okay.	2023-03-24	3
25	25	14	Zu viel Kitsch, zu wenig Substanz.	2023-03-25	2
26	26	19	Sehr guter Thriller, hat mich total gepackt.	2023-03-26	5
27	27	18	Wirklich langweilig, keine Höhepunkte.	2023-03-27	1
28	28	21	Langeweile pur, aber das Ende war gut.	2023-03-28	3
29	29	22	Besser als erwartet, eine angenehme Lektüre.	2023-03-29	4
30	30	4	Fesselnde Story, großartige Charaktere!	2023-03-30	5
31	31	8	Wenig überzeugend, ich hatte mehr erwartet.	2023-03-31	2
32	32	11	Sehr tiefgründig, aber etwas langatmig.	2023-04-01	4
33	60	13	Ein Muss für alle Fantasy-Fans!	2023-04-02	5
34	34	6	Tolle Erzählweise, jedoch zu wenig Action.	2023-04-03	3
35	35	9	Ergreifend und emotional, hat mich sehr berührt.	2023-04-04	5
36	66	12	Ganz nett, aber nicht wirklich originell.	2023-04-05	3
37	66	15	Das Buch hat mich tief bewegt, sehr zu empfehlen!	2023-04-06	5
38	38	23	Habe mehr erwartet, leider enttäuscht.	2023-04-07	2
39	39	7	Sehr spannend und temporeich.	2023-04-08	4
40	40	10	Gute Idee, aber schlecht umgesetzt.	2023-04-09	2
41	41	16	Fantastisches Buch, man muss es einfach lesen!	2023-04-10	5
42	42	24	War etwas zu lang, aber insgesamt gut.	2023-04-11	4
43	43	19	Nicht schlecht, aber der Funke ist nicht übergesprungen.	2023-04-12	3
44	44	6	Richtig packend bis zur letzten Seite.	2023-04-13	5
45	45	25	Zu viele Klischees, hat mir nicht gefallen.	2023-04-14	2
46	46	3	Witzig und charmant, hat mir gut gefallen.	2023-04-15	4
47	47	27	Eines der besten Bücher, die ich je gelesen habe!	2023-04-16	5
48	48	8	Durchschnittlich, keine Überraschungen.	2023-04-17	3
49	49	30	Unglaublich spannend und voller Wendungen!	2023-04-18	5
50	50	28	Der Plot war schwach, das Ende enttäuschend.	2023-04-19	2
51	51	9	Sehr unterhaltsam und leicht zu lesen.	2023-04-20	4
52	52	17	Hat mich leider nicht überzeugt, zu wenig Tiefgang.	2023-04-21	2
53	53	29	Absolut fesselnd, kann es kaum erwarten, mehr zu lesen!	2023-04-22	5
54	54	13	Das Buch hat viel Potenzial, aber nicht voll ausgeschöpft.	2023-04-23	3
55	55	25	Die besten 300 Seiten, die ich je gelesen habe.	2023-04-24	5
56	56	12	Gut geschrieben, aber irgendwie vorhersehbar.	2023-04-25	3
57	57	2	Fantastisch, ich konnte nicht aufhören zu lesen!	2023-04-26	5
58	58	6	Enttäuschend, hatte mir mehr erwartet.	2023-04-27	2
59	59	30	Ungewöhnlich und spannend, gut recherchiert.	2023-04-28	4
60	60	15	Überraschend gut, hat mir gefallen.	2023-04-29	4
61	61	8	Ein Klassiker, den man unbedingt gelesen haben muss.	2023-04-30	5
62	62	24	War zu vorhersehbar, keine großen Überraschungen.	2023-05-01	3
63	63	9	Der perfekte Thriller, ich habe es geliebt!	2023-05-02	5
64	64	17	Viel zu lang, aber die Charaktere waren interessant.	2023-05-03	3
65	65	14	Sehr gut geschrieben, hat mich berührt.	2023-05-04	5
66	66	11	Nicht mein Genre, aber immer noch gut gemacht.	2023-05-05	4
67	67	20	Einfach zu lang, aber trotzdem spannend.	2023-05-06	4
68	68	4	Gute Story, aber viele Schwächen.	2023-05-07	3
69	69	5	Sehr beeindruckend und gut recherchiert.	2023-05-08	5
70	70	2	Leider enttäuschend, das Buch zog sich.	2023-05-09	2
71	71	3	Tolle Wendungen, aber etwas langatmig.	2023-05-10	4
72	72	22	Spannend und gut geschrieben, aber das Ende war zu schnell.	2023-05-11	4
73	73	6	Ich konnte nicht aufhören zu lesen, fantastisch!	2023-05-12	5
74	74	7	Nicht besonders herausragend, aber solide.	2023-05-13	3
75	75	25	Ein echter Page-Turner, sehr empfehlenswert.	2023-05-14	5
76	76	9	Gut, aber das Ende war zu vorhersehbar.	2023-05-15	3
77	77	14	Ein absoluter Klassiker, den man nicht missen sollte.	2023-05-16	5
78	78	21	Hat mich begeistert, aber einige Längen.	2023-05-17	4
79	79	3	Zu viele Klischees, nicht sehr originell.	2023-05-18	2
80	80	17	Perfekt für Fans dieses Genres!	2023-05-19	5
\.


--
-- Data for Name: waitlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.waitlist (waitlist_id, user_id, book_id, checkout_date, return_date, status) FROM stdin;
1	1	3	2023-01-01	2023-01-14	available
2	2	5	2023-01-02	2023-01-16	available
3	2	8	2023-01-03	2023-01-17	available
4	3	10	2023-01-04	2023-01-18	available
5	4	12	2023-01-05	2023-01-19	available
6	5	6	2023-01-06	2023-01-20	available
7	6	15	2023-01-07	2023-01-21	available
8	7	7	2023-01-08	2023-01-22	available
9	8	20	2023-01-09	2023-01-23	available
10	9	1	2023-01-10	2023-01-24	available
11	9	3	2023-01-11	2023-01-25	available
12	10	17	2023-01-12	2023-01-26	available
13	11	14	2023-01-13	2023-01-27	available
14	22	4	2023-01-14	2023-01-28	available
15	13	9	2023-01-15	2023-01-29	available
16	14	13	2023-01-16	2023-01-30	available
17	15	18	2023-01-17	2023-01-31	available
18	16	16	2023-01-18	\N	waiting
19	22	11	2023-01-19	\N	waiting
20	56	5	2023-01-20	\N	waiting
21	56	2	2023-01-21	\N	waiting
22	20	12	2023-01-22	\N	waiting
23	21	8	2023-01-23	\N	waiting
24	22	6	2023-01-24	\N	waiting
25	78	14	2023-01-25	\N	waiting
26	24	3	2023-01-26	\N	waiting
27	83	16	2023-01-27	\N	waiting
28	26	1	2023-01-28	\N	waiting
29	27	4	2023-01-29	\N	waiting
30	28	18	2023-01-30	\N	waiting
31	77	9	2023-01-31	\N	waiting
32	30	13	2023-02-01	\N	waiting
33	31	15	2023-02-02	\N	waiting
34	53	8	2023-02-03	\N	waiting
35	33	7	2023-02-04	\N	waiting
36	34	5	2023-02-05	\N	waiting
37	35	17	2023-02-06	\N	waiting
38	36	3	2023-02-07	\N	waiting
39	37	2	2023-02-08	\N	waiting
40	38	14	2023-02-09	\N	waiting
41	39	6	2023-02-10	\N	waiting
42	40	4	2023-02-11	\N	waiting
43	41	12	2023-02-12	\N	waiting
44	42	9	2023-02-13	\N	waiting
45	43	8	2023-02-14	\N	waiting
46	44	5	2023-02-15	\N	waiting
\.


--
-- Name: address_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.address_address_id_seq', 100, true);


--
-- Name: book_book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_book_id_seq', 123, true);


--
-- Name: contact_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contact_contact_id_seq', 1, false);


--
-- Name: keyword_keyword_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.keyword_keyword_id_seq', 82, true);


--
-- Name: lending_lending_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lending_lending_id_seq', 40, true);


--
-- Name: person_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_user_id_seq', 100, true);


--
-- Name: review_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.review_review_id_seq', 88, true);


--
-- Name: waitlist_waitlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.waitlist_waitlist_id_seq', 46, true);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (address_id);


--
-- Name: book book_isbn_long_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_isbn_long_key UNIQUE (isbn_long);


--
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (book_id);


--
-- Name: contact contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_pkey PRIMARY KEY (contact_id);


--
-- Name: keyword keyword_keyword_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.keyword
    ADD CONSTRAINT keyword_keyword_key UNIQUE (keyword);


--
-- Name: keyword keyword_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.keyword
    ADD CONSTRAINT keyword_pkey PRIMARY KEY (keyword_id);


--
-- Name: lending lending_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lending
    ADD CONSTRAINT lending_pkey PRIMARY KEY (lending_id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (user_id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (review_id);


--
-- Name: waitlist waitlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waitlist
    ADD CONSTRAINT waitlist_pkey PRIMARY KEY (waitlist_id);


--
-- Name: lending trigger_set_due_date; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trigger_set_due_date BEFORE INSERT ON public.lending FOR EACH ROW EXECUTE FUNCTION public.set_due_date();


--
-- Name: lending trigger_set_return_date; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trigger_set_return_date BEFORE UPDATE ON public.lending FOR EACH ROW EXECUTE FUNCTION public.set_return_date();


--
-- Name: address address_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.person(user_id) ON DELETE CASCADE;


--
-- Name: book book_keyword_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES public.keyword(keyword_id) ON DELETE SET NULL;


--
-- Name: contact contact_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.person(user_id) ON DELETE CASCADE;


--
-- Name: lending lending_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lending
    ADD CONSTRAINT lending_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.book(book_id) ON DELETE CASCADE;


--
-- Name: lending lending_user_id_borrower_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lending
    ADD CONSTRAINT lending_user_id_borrower_fkey FOREIGN KEY (user_id_borrower) REFERENCES public.person(user_id) ON DELETE CASCADE;


--
-- Name: lending lending_user_id_worker_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lending
    ADD CONSTRAINT lending_user_id_worker_fkey FOREIGN KEY (user_id_worker) REFERENCES public.person(user_id) ON DELETE CASCADE;


--
-- Name: review review_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.book(book_id) ON DELETE CASCADE;


--
-- Name: review review_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.person(user_id) ON DELETE CASCADE;


--
-- Name: waitlist waitlist_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waitlist
    ADD CONSTRAINT waitlist_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.book(book_id) ON DELETE CASCADE;


--
-- Name: waitlist waitlist_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waitlist
    ADD CONSTRAINT waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.person(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

